import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import http from "@/server/config/http"
import Login from "@/components/login"
import { sendRegisterEmail } from "@/server/sendMail"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

//Get menu
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await http.get<any>('menu');
  return (
    <html lang="en">
      <body className="select-none">
        <Header menu={menu.data} />
        <div className="flex min-h-[calc(100vh-65px)] bg-zinc-50 font-sans dark:bg-black pt-[10px] justify-center">
          <div>
            {children}
          </div>
          <div>
            <Login />
          </div>
        </div>
      </body>
    </html>
  );
}
